# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-17 09:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pokeDjangoRestApi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainer',
            name='image',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='pokeDjangoRestApi.Image'),
        ),
    ]
